command:
  - uvicorn
  - backend.main:app
  - --host=0.0.0.0
  - --port=8000
env:
  - name: CATALOG
    value: vdm_classic_rikfy0_catalog
  - name: SCHEMA
    value: coupon_mgmt
  - name: DATABRICKS_WAREHOUSE_ID
    value: 708f9ebed64875ba
resources:
  - name: warehouse
    sql_warehouse:
      id: 708f9ebed64875ba
      permission: CAN_USE
